### ISSUE TITLE
Problem with Phantom omni with UR5 real hardware

### ISSUE THREAD

**Issue by chenjq20** [sunghowoo/Control-of-two-UR5s-by-two-phantom-omnies-#1]
Hi,

Thank you for your kind share of the control method. I have tried the launch process and succeeded in most of the steps. My environment is the same with the description in "README.md".

I wonder if I could modified this project to control UR5 real hardware by phantom omni. I have tried to connect the UR5 hardware and phantom omni simultaneously and it seemed that the two connections were successful. I typed this command before other launch to control the UR5 real hardware:

> roslaunch ur_bringup ur5_bringup.launch

Though I failed in controlling the UR5 real hardware, I wonder if it is possible to modify this project to control UR5 real hardware.

Also, I met some problem when trying to launch with Rviz using:

> roslaunch geomagic_control geomagic.launch

The error messages were as followed:

> Fail to initialize haptic device
/opt/ros/kinetic/lib/rviz/rviz/symbol lookup error:/opt/ros/kinetic/lib/librviz.so:undefined symbol:_ZNK9QRTreeViewportSizeHintEv

This seems to be a common problem when controlling phantom omni with Ubuntu 16.04. I wonder how I could solve this problem.

Thank you for any help you can offer!

**Comment by sunghowoo** [comment]
Hi. Thank you for interesting in my old project :) Well, for your first question, I had not tried to control a real UR5 but I believe the basic communication algorithm is the same as the simulation process. if the real hardware can do ROS communication, it will work. I suggest simulating UR5 on Gazebo and move to control your real robot. For your second question, "Fail to initialize haptic device" maybe be caused by the haptic driver.  What I struggled with before is finding an old haptic driver which communicates with ROS kinetic version. <https://support.3dsystems.com/s/article/Haptic-Device-Drivers?language=en_US > this website would be helpful to solve your connection error.  I figured out this driver works so it will work fine if you solved some ros dependency issues. Sorry I cannot help that much!  Good luck with your project. please let me know your project works later :).
